namespace DutyPlanner.Infrastructure.Settings
{
    public class AppSettings
    {
        public string DataFolderPath { get; set; } = "Data";
        public bool OpenPdfAfterExport { get; set; } = true;

        public bool OpenExcelAfterExport { get; set; } = true;
        public string DefaultExportFolder { get; set; } = "Exports";

        public string Language { get; set; } = "ru";

        // состояние приложения
        public int? LastOpenedYear { get; set; }
        public int? LastOpenedMonth { get; set; }

        public int YearStartMonth { get; set; } = 1; // 1–12

        public int MinimumHours { get; set; } = 72;

        public List<DayOfWeek> AutoGenerateDays { get; set; } =
            [DayOfWeek.Friday, DayOfWeek.Saturday];
    }
}
